#!/usr/bin/ruby -w
require 'digest/md5'

$PKG_FILE=ARGV[0]
$EXPECTED_DIGEST=ARGV[1]

digest = Digest::MD5.hexdigest( File.read($PKG_FILE) )

if digest == $EXPECTED_DIGEST then
	print "File #{$PKG_FILE} matches checksum\n"
	exit 0
else
	print "File #{$PKG_FILE} does NOT match checksum\n"
	exit 1
end

__END__

