#!/usr/bin/ruby -w
require 'digest/md5'

$PKG_FILE=ARGV[0]
$EXPECTED_DIGEST=ARGV[1]

if not File.exists?($PKG_FILE) then
	print "File #{$PKG_FILE} does not exist.\n"
	exit 1
end

digest = Digest::MD5.hexdigest( File.read($PKG_FILE) )

if digest == $EXPECTED_DIGEST then
	exit 0
else
	exit 1
end

__END__

